[project]
name = "python-asteroids"
version = "0.1.0"
description = "Boot.dev project, building asteroids game with python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
